# Video 9: Cleaning Data - Casting Datatypes and Handling Missing Values

## Learning Objective
In this notebook I am learning how to find and handle missing values in a DataFrame, how to replace
custom missing value markers, and how to convert a column into the correct data type.

## Step 1: Import Pandas and NumPy

In [1]:
import pandas as pd
import numpy as np

## Step 2: A Small Example DataFrame with Missing Values
I made this small example on purpose so it has different kinds of missing values, like NaN, None, and the text 'Missing'.

In [2]:
people = {
    'first': ['John', 'Jane', 'Sam', np.nan, None, 'NA'],
    'last': ['Doe', 'Smith', np.nan, np.nan, 'Missing', 'Missing'],
    'email': ['JohnDoe@email.com', 'JaneSmith@email.com', 'SamBrown@email.com', np.nan, None, 'Anonymous@email.com'],
    'age': ['33', '55', '63', np.nan, None, 'Missing']
}
small_df = pd.DataFrame(people)

In [3]:
small_df

  first     last                email      age
0  John      Doe    JohnDoe@email.com       33
1  Jane    Smith  JaneSmith@email.com       55
2   Sam      NaN   SamBrown@email.com       63
3   NaN      NaN                  NaN      NaN
4   NaN  Missing                  NaN      NaN
5    NA  Missing  Anonymous@email.com  Missing

## Step 3: Dropping Missing Values
By default, dropna removes any row that has at least one missing value.

In [4]:
small_df.dropna()

  first     last                email      age
0  John      Doe    JohnDoe@email.com       33
1  Jane    Smith  JaneSmith@email.com       55
5    NA  Missing  Anonymous@email.com  Missing

I can be more specific about how dropna should work.

In [5]:
small_df.dropna(axis='index', how='any')

  first     last                email      age
0  John      Doe    JohnDoe@email.com       33
1  Jane    Smith  JaneSmith@email.com       55
5    NA  Missing  Anonymous@email.com  Missing

In [6]:
small_df.dropna(axis='index', how='all')

  first     last                email      age
0  John      Doe    JohnDoe@email.com       33
1  Jane    Smith  JaneSmith@email.com       55
2   Sam      NaN   SamBrown@email.com       63
4   NaN  Missing                  NaN      NaN
5    NA  Missing  Anonymous@email.com  Missing

In [7]:
small_df.dropna(axis='columns', how='any')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]

I can also drop rows only if a specific column has a missing value.

In [8]:
small_df.dropna(axis='index', how='any', subset=['last'])

  first     last                email      age
0  John      Doe    JohnDoe@email.com       33
1  Jane    Smith  JaneSmith@email.com       55
4   NaN  Missing                  NaN      NaN
5    NA  Missing  Anonymous@email.com  Missing

## Step 4: Replacing Custom Missing Value Markers
Right now, 'NA' and 'Missing' are just normal text, not real missing values. I need to convert them into proper NaN values first.

In [9]:
small_df.replace('NA', np.nan, inplace=True)

  first     last                email      age
0  John      Doe    JohnDoe@email.com       33
1  Jane    Smith  JaneSmith@email.com       55
2   Sam      NaN   SamBrown@email.com       63
3   NaN      NaN                  NaN      NaN
4   NaN  Missing                  NaN      NaN
5   NaN  Missing  Anonymous@email.com  Missing

In [10]:
small_df.replace('Missing', np.nan, inplace=True)

  first   last                email  age
0  John    Doe    JohnDoe@email.com   33
1  Jane  Smith  JaneSmith@email.com   55
2   Sam    NaN   SamBrown@email.com   63
3   NaN    NaN                  NaN  NaN
4   NaN    NaN                  NaN  NaN
5   NaN    NaN  Anonymous@email.com  NaN

In [11]:
small_df

  first   last                email  age
0  John    Doe    JohnDoe@email.com   33
1  Jane  Smith  JaneSmith@email.com   55
2   Sam    NaN   SamBrown@email.com   63
3   NaN    NaN                  NaN  NaN
4   NaN    NaN                  NaN  NaN
5   NaN    NaN  Anonymous@email.com  NaN

## Step 5: Checking for Missing Values with isna

In [12]:
small_df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False   True  False  False
3   True   True   True   True
4   True   True   True   True
5   True   True  False   True

## Step 6: Filling Missing Values

In [13]:
small_df.fillna('MISSING')

     first     last                email      age
0     John      Doe    JohnDoe@email.com       33
1     Jane    Smith  JaneSmith@email.com       55
2      Sam  MISSING   SamBrown@email.com       63
3  MISSING  MISSING              MISSING  MISSING
4  MISSING  MISSING              MISSING  MISSING
5  MISSING  MISSING  Anonymous@email.com  MISSING

## Step 7: Casting Data Types
Right now, the age column is stored as text, even though it holds numbers.

In [14]:
small_df.dtypes

first    str
last     str
email    str
age      str
dtype: object

In [15]:
small_df['age'] = small_df['age'].astype(float)

In [16]:
small_df.dtypes

first        str
last         str
email        str
age      float64
dtype: object

Now that age is a number, I can run numeric functions like mean on it.

In [17]:
small_df['age'].mean()

np.float64(50.333333333333336)

## Step 8: Apply These Skills on the Survey Data
The survey data uses custom text like 'NA' and 'Missing' for its missing values. I will load it again, but this time I will tell Pandas to treat these values as missing right away.

In [18]:
na_vals = ['NA', 'Missing']
df = pd.read_csv('results.csv', na_values=na_vals)

## Step 9: Cleaning the YearsCode Column
The YearsCode column has some text answers mixed in with the numbers, like 'Less than 1 year' and 'More than 50 years'.

In [19]:
df['YearsCode'].unique()

<StringArray>
[                 '4',                  nan,                  '3',
                 '16',                 '13',                  '6',
                  '8',                 '12',                  '2',
                  '5',                 '17',                 '10',
                 '14',                 '35',                  '7',
   'Less than 1 year',                 '30',                  '9',
                 '26',                 '40',                 '19',
                 '15',                 '20',                 '28',
                 '25',                  '1',                 '22',
                 '11',                 '33',                 '50',
                 '41',                 '18',                 '34',
                 '24',                 '23',                 '42',
                 '27',                 '21',                 '36',
                 '32',                 '39',                 '38',
                 '31',                 '37', 'More than 50 years',
                 '29',                 '44',                 '45',
                 '48',                 '46',                 '43',
                 '47',                 '49']
Length: 53, dtype: str

In [20]:
df['YearsCode'] = df['YearsCode'].replace('Less than 1 year', 0)

In [21]:
df['YearsCode'] = df['YearsCode'].replace('More than 50 years', 51)

## Step 10: Converting YearsCode to a Number

In [22]:
df['YearsCode'] = df['YearsCode'].astype(float)

Now I can run numeric functions on this column.

In [23]:
df['YearsCode'].mean()

np.float64(11.662114216834588)

In [24]:
df['YearsCode'].median()

np.float64(9.0)