# Video 5: Updating Rows and Columns - Modifying Data Within DataFrames

## Learning Objective
In this notebook I am learning how to rename columns, update values in rows and columns, and use
apply, map, and replace to change data inside a DataFrame.

## Step 1: Import Pandas and Load the Data

In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [3]:
df = pd.read_csv('results.csv')

In [4]:
schema_df = pd.read_csv('schema.csv')

## Step 2: A Small Example DataFrame

In [5]:
people = {
    'first': ['John', 'Jane', 'Sam'],
    'last': ['Doe', 'Smith', 'Brown'],
    'email': ['JohnDoe@email.com', 'JaneSmith@email.com', 'SamBrown@email.com']
}
people_df = pd.DataFrame(people)

## Step 3: Renaming All Columns at Once

In [6]:
people_df.columns = ['first_name', 'last_name', 'email']

In [7]:
people_df

  first_name last_name                email
0       John       Doe    JohnDoe@email.com
1       Jane     Smith  JaneSmith@email.com
2        Sam     Brown   SamBrown@email.com

## Step 4: Renaming Columns with a Loop

In [8]:
people_df.columns = [x.upper() for x in people_df.columns]

In [9]:
people_df

  FIRST_NAME LAST_NAME                EMAIL
0       John       Doe    JohnDoe@email.com
1       Jane     Smith  JaneSmith@email.com
2        Sam     Brown   SamBrown@email.com

## Step 5: Renaming Specific Columns with rename
This is the safest way to rename columns because I only need to mention the ones I want to change.

In [10]:
people_df.rename(columns={
    'FIRST_NAME': 'first',
    'LAST_NAME': 'last',
    'EMAIL': 'email'
}, inplace=True)

In [11]:
people_df

  first   last                email
0  John    Doe    JohnDoe@email.com
1  Jane  Smith  JaneSmith@email.com
2   Sam  Brown   SamBrown@email.com

## Step 6: Updating a Single Row

In [12]:
people_df.loc[2]

first                   Sam
last                  Brown
email    SamBrown@email.com
Name: 2, dtype: str

In [13]:
people_df.loc[2] = ['John', 'Smith', 'JohnSmith@email.com']

In [14]:
people_df

  first   last                email
0  John    Doe    JohnDoe@email.com
1  Jane  Smith  JaneSmith@email.com
2  John  Smith  JohnSmith@email.com

## Step 7: Updating a Single Value

In [15]:
people_df.loc[2, 'last'] = 'Doe'

In [16]:
people_df

  first   last                email
0  John    Doe    JohnDoe@email.com
1  Jane  Smith  JaneSmith@email.com
2  John    Doe  JohnSmith@email.com

## Step 8: Updating Values that Match a Filter

In [17]:
filt = (people_df['email'] == 'JohnSmith@email.com')
people_df.loc[filt, 'last'] = 'Smith'

In [18]:
people_df

  first   last                email
0  John    Doe    JohnDoe@email.com
1  Jane  Smith  JaneSmith@email.com
2  John  Smith  JohnSmith@email.com

## Step 9: Updating a Whole Column with apply
The apply method runs a function on every value in a Series.

In [19]:
people_df['email'].apply(len)

0    17
1    19
2    19
Name: email, dtype: int64

In [20]:
def update_email(email):
    return email.upper()

people_df['email'] = people_df['email'].apply(update_email)

In [21]:
people_df

  first   last                email
0  John    Doe    JOHNDOE@EMAIL.COM
1  Jane  Smith  JANESMITH@EMAIL.COM
2  John  Smith  JOHNSMITH@EMAIL.COM

I can also use apply with a lambda function instead of writing a full function.

In [22]:
people_df['email'] = people_df['email'].apply(lambda x: x.lower())

In [23]:
people_df

  first   last                email
0  John    Doe    johndoe@email.com
1  Jane  Smith  janesmith@email.com
2  John  Smith  johnsmith@email.com

## Step 10: Using map and replace
map will change values that are not listed into missing values, while replace keeps values that are not listed the same.

In [24]:
people_df['first'].map({'John': 'Chris', 'Jane': 'Mary'})

0    Chris
1     Mary
2    Chris
Name: first, dtype: str

In [25]:
people_df['first'] = people_df['first'].replace({'John': 'Chris', 'Jane': 'Mary'})

In [26]:
people_df

   first   last                email
0  Chris    Doe    johndoe@email.com
1   Mary  Smith  janesmith@email.com
2  Chris  Smith  johnsmith@email.com

## Step 11: Apply These Skills on the Survey Data

### Renaming a Column

In [27]:
df.rename(columns={'ConvertedComp': 'SalaryUSD'}, inplace=True)
df['SalaryUSD']

0            NaN
1            NaN
2         8820.0
3        61000.0
4            NaN
          ...
88878        NaN
88879        NaN
88880        NaN
88881        NaN
88882        NaN
Name: SalaryUSD, Length: 88883, dtype: float64

### Changing Yes and No into True and False

In [28]:
df['Hobbyist']

0        Yes
1         No
2        Yes
3         No
4        Yes
        ...
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: str

In [29]:
df['Hobbyist'] = df['Hobbyist'].map({'Yes': True, 'No': False})
df['Hobbyist']

0         True
1        False
2         True
3        False
4         True
         ...
88878     True
88879    False
88880    False
88881    False
88882     True
Name: Hobbyist, Length: 88883, dtype: bool