# Video 2: DataFrame and Series Basics - Selecting Rows and Columns

## Learning Objective
In this notebook I am learning the difference between a Series and a DataFrame, and how to select
specific rows and columns from a DataFrame using different methods.

## Step 1: Import Pandas and Load the Data

In [1]:
import pandas as pd

In [2]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

In [3]:
df = pd.read_csv('results.csv')

In [4]:
schema_df = pd.read_csv('schema.csv')

## Step 2: A Small Example DataFrame
I will use this small example to practice the basics before using the survey data.

In [5]:
people = {
    'first': ['John', 'Jane', 'Sam'],
    'last': ['Doe', 'Smith', 'Brown'],
    'email': ['JohnDoe@email.com', 'JaneSmith@email.com', 'SamBrown@email.com']
}
people_df = pd.DataFrame(people)

## Step 3: Series vs DataFrame
A single column from a DataFrame is called a Series. A DataFrame is basically a container of Series that share the same index.

In [6]:
people_df['email']

0      JohnDoe@email.com
1    JaneSmith@email.com
2     SamBrown@email.com
Name: email, dtype: str

In [7]:
type(people_df['email'])

pandas.Series

In [8]:
type(people_df)

pandas.DataFrame

## Step 4: Selecting a Single Column

In [9]:
people_df['last']

0      Doe
1    Smith
2    Brown
Name: last, dtype: str

## Step 5: Selecting Multiple Columns
To select more than one column, I pass a list of column names.

In [10]:
people_df[['last', 'email']]

    last                email
0    Doe    JohnDoe@email.com
1  Smith  JaneSmith@email.com
2  Brown   SamBrown@email.com

## Step 6: Viewing All Column Names

In [11]:
people_df.columns

Index(['first', 'last', 'email'], dtype='str')

## Step 7: Selecting Rows with iloc
iloc lets me select rows and columns using their integer position.

In [12]:
people_df.iloc[0]

first                 John
last                   Doe
email    JohnDoe@email.com
Name: 0, dtype: str

In [13]:
people_df.iloc[[0, 1]]

  first   last                email
0  John    Doe    JohnDoe@email.com
1  Jane  Smith  JaneSmith@email.com

In [14]:
people_df.iloc[[0, 1], 2]

0      JohnDoe@email.com
1    JaneSmith@email.com
Name: email, dtype: str

## Step 8: Selecting Rows with loc
loc lets me select rows and columns using their labels instead of their position.

In [15]:
people_df.loc[0]

first                 John
last                   Doe
email    JohnDoe@email.com
Name: 0, dtype: str

In [16]:
people_df.loc[[0, 1]]

  first   last                email
0  John    Doe    JohnDoe@email.com
1  Jane  Smith  JaneSmith@email.com

In [17]:
people_df.loc[[0, 1], ['email', 'last']]

                 email   last
0    JohnDoe@email.com    Doe
1  JaneSmith@email.com  Smith

In [18]:
people_df.loc[0:1, 'last':'email']

    last                email
0    Doe    JohnDoe@email.com
1  Smith  JaneSmith@email.com

## Step 9: Apply These Skills on the Survey Data
Now I will use the same selection methods on the real survey dataset.

In [19]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='str')

Selecting a single column from the survey data.

In [20]:
df['Hobbyist']

0        Yes
1         No
2        Yes
3         No
4        Yes
        ...
88878    Yes
88879     No
88880     No
88881     No
88882    Yes
Name: Hobbyist, Length: 88883, dtype: str

Selecting a few columns at once.

In [21]:
df[['Country', 'Employment', 'ConvertedComp']]

,Country,Employment,ConvertedComp
0,United Kingdom,"Not employed, and not looking for work",NaN
1,Bosnia and Herzegovina,"Not employed, but looking for work",NaN
2,Thailand,Employed full-time,8820.0
3,United States,Employed full-time,61000.0
4,Ukraine,Employed full-time,NaN
...,...,...,...
88878,Canada,"Not employed, and not looking for work",NaN
88879,NaN,NaN,NaN
88880,NaN,Employed full-time,NaN
88881,NaN,"Independent contractor, freelancer, or self-em...",NaN
88882,Spain,"Not employed, and not looking for work",NaN

Selecting one row using loc.

In [22]:
df.loc[0]

Respondent                                                                1
MainBranch                           I am a student who is learning to code
Hobbyist                                                                Yes
OpenSourcer                                                           Never
OpenSource                The quality of OSS and closed source software ...
Employment                           Not employed, and not looking for work
Country                                                      United Kingdom
Student                                                                  No
EdLevel                                           Primary/elementary school
UndergradMajor                                                          NaN
EduOther                  Taught yourself a new language, framework, or ...
OrgSize                                                                 NaN
DevType                                                                 NaN
YearsCode                                                                 4
Age1stCode                                                               10
YearsCodePro                                                            NaN
CareerSat                                                               NaN
JobSat                                                                  NaN
MgrIdiot                                                                NaN
MgrMoney                                                                NaN
MgrWant                                                                 NaN
JobSeek                                                                 NaN
LastHireDate                                                            NaN
LastInt                                                                 NaN
FizzBuzz                                                                NaN
JobFactors                                                              NaN
ResumeUpdate                                                            NaN
CurrencySymbol                                                          NaN
CurrencyDesc                                                            NaN
CompTotal                                                               NaN
CompFreq                                                                NaN
ConvertedComp                                                           NaN
WorkWeekHrs                                                             NaN
WorkPlan                                                                NaN
WorkChallenge                                                           NaN
WorkRemote                                                              NaN
WorkLoc                                                                 NaN
ImpSyn                                                                  NaN
CodeRev                                                                 NaN
CodeRevHrs                                                              NaN
UnitTests                                                               NaN
PurchaseHow                                                             NaN
PurchaseWhat                                                            NaN
LanguageWorkedWith                          HTML/CSS;Java;JavaScript;Python
LanguageDesireNextYear      C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL
DatabaseWorkedWith                                                   SQLite
DatabaseDesireNextYear                                                MySQL
PlatformWorkedWith                                            MacOS;Windows
PlatformDesireNextYear                              Android;Arduino;Windows
WebFrameWorkedWith                                             Django;Flask
WebFrameDesireNextYear                                         Flask;jQuery
MiscTechWorkedWith                                                  Node.js
MiscTechDesireNextYear                                              Node.js
DevEnviron                                       IntelliJ;Notepad++;PyCharm
OpSys                                                               Windows
Containers                                          I do not use containers
BlockchainOrg                                                           NaN
BlockchainIs                                                            NaN
BetterLife                                                              Yes
ITperson                           Fortunately, someone else has that title
OffOn                                                                   Yes
SocialMedia                                                         Twitter
Extraversion                                                         Online
ScreenName                                                         Username
SOVisit1st                                                             2017
SOVisitFreq                                 A few times per month or weekly
SOVisitTo                 Find answers to specific questions;Learn how t...
SOFindAnswer                                             3-5 times per week
SOTimeSaved                                  Stack Overflow was much faster
SOHowMuchTime                                                 31-60 minutes
SOAccount                                                                No
SOPartFreq                                                              NaN
SOJobs                    No, I didn't know that Stack Overflow had a jo...
EntTeams                                No, and I don't know what those are
SOComm                                                              Neutral
WelcomeChange                       Just as welcome now as I felt last year
SONewContent              Tech articles written by other developers;Indu...
Age                                                                    14.0
Gender                                                                  Man
Trans                                                                    No
Sexuality                                           Straight / Heterosexual
Ethnicity                                                               NaN
Dependents                                                               No
SurveyLength                                          Appropriate in length
SurveyEase                                       Neither easy nor difficult
Name: 0, dtype: object

Selecting a range of rows and columns using loc.

In [23]:
df.loc[0:2, 'Hobbyist':'Employment']

,Hobbyist,OpenSourcer,OpenSource,Employment
0,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work"
1,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work"
2,Yes,Never,The quality of OSS and closed source software ...,Employed full-time

Counting the different values in a column, which is very useful when exploring survey data.

In [24]:
df['Hobbyist'].value_counts()

Hobbyist
Yes    71257
No     17626
Name: count, dtype: int64