# Video 11: Reading/Writing Data to Different Sources - Excel, JSON, SQL, Etc.

## Learning Objective
In this notebook I am learning how to read and write data using different file formats, including
CSV, Excel, JSON, and SQL.

## Step 1: Import Pandas and sqlite3

In [1]:
import pandas as pd
import sqlite3

In [2]:
pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

## Step 2: Load the Survey Data

In [3]:
df = pd.read_csv('results.csv')

## Step 3: Create a Smaller Sample of the Data
The full survey has almost 89,000 rows, so for this video I will just work with a small sample and a few columns to keep things fast and easy to look at.

In [4]:
small_df = df[['Respondent', 'Country', 'ConvertedComp', 'LanguageWorkedWith']].head(50)

In [5]:
small_df

,Respondent,Country,ConvertedComp,LanguageWorkedWith
0,1,United Kingdom,NaN,HTML/CSS;Java;JavaScript;Python
1,2,Bosnia and Herzegovina,NaN,C++;HTML/CSS;Python
2,3,Thailand,8820.0,HTML/CSS
3,4,United States,61000.0,C;C++;C#;Python;SQL
4,5,Ukraine,NaN,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA
5,6,Canada,366420.0,Java;R;SQL
6,7,Ukraine,NaN,HTML/CSS;JavaScript
7,8,India,NaN,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
8,9,New Zealand,95179.0,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...
9,10,India,13293.0,C#;Go;JavaScript;Python;R;SQL
10,11,Antigua and Barbuda,NaN,Other(s):
11,12,Canada,NaN,Bash/Shell/PowerShell;HTML/CSS;Java;Python;R;SQL
12,13,United States,90000.0,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...
13,14,Germany,57060.0,C++
14,15,India,NaN,Assembly;Bash/Shell/PowerShell;C;C++;HTML/CSS;...
15,16,United Kingdom,455352.0,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;T...
16,17,Australia,65277.0,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Type...
17,18,Russian Federation,21996.0,Python;R
18,19,Brazil,31140.0,C#;HTML/CSS;Java;JavaScript;SQL;TypeScript
19,20,Lithuania,41244.0,Bash/Shell/PowerShell;C#;HTML/CSS;Java;JavaScr...
20,21,Canada,NaN,Assembly;Bash/Shell/PowerShell;C;C++;Go;Java;J...
21,22,United States,103000.0,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...
22,23,United States,69000.0,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Pyth...
23,24,Israel,26388.0,HTML/CSS;JavaScript;PHP;TypeScript
24,25,South Africa,6300.0,HTML/CSS;JavaScript;PHP;SQL;TypeScript
25,26,United States,114000.0,Bash/Shell/PowerShell;C++;C#;HTML/CSS;JavaScri...
26,27,Colombia,NaN,C++;JavaScript;Python;Ruby;SQL;TypeScript
27,28,Turkey,NaN,JavaScript;TypeScript
28,29,United States,100000.0,Bash/Shell/PowerShell;JavaScript;SQL
29,30,Switzerland,90417.0,NaN
30,31,Canada,NaN,Python
31,32,United States,1100000.0,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...
32,33,Argentina,8400.0,C++;Python;R
33,34,Sri Lanka,NaN,HTML/CSS;JavaScript
34,35,United States,80000.0,HTML/CSS;JavaScript
35,36,Germany,20628.0,Java;Kotlin;Python
36,37,Canada,NaN,Bash/Shell/PowerShell;JavaScript;Python;Other(s):
37,38,Czech Republic,51312.0,C#;HTML/CSS;JavaScript;SQL
38,39,United States,156000.0,C#;JavaScript;SQL;TypeScript
39,40,Denmark,NaN,C#;HTML/CSS
40,41,Malaysia,NaN,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
41,42,Bangladesh,NaN,HTML/CSS;JavaScript;PHP;TypeScript
42,43,Spain,20623.0,C++;C#;HTML/CSS;Java;JavaScript;Objective-C;SQL
43,44,Germany,87996.0,Bash/Shell/PowerShell;C#;HTML/CSS;Java;JavaScr...
44,45,United States,175000.0,Python
45,46,United States,NaN,Bash/Shell/PowerShell;C;C#;HTML/CSS;JavaScript...
46,47,United States,187000.0,Java;PHP;Ruby
47,48,Russian Federation,NaN,HTML/CSS;PHP;SQL
48,49,Serbia,60000.0,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...
49,50,India,5597.0,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...

## Step 4: Writing to a CSV File

In [6]:
small_df.to_csv('survey_sample.csv', index=False)

## Step 5: Reading a CSV File Back In

In [7]:
csv_df = pd.read_csv('survey_sample.csv')

In [8]:
csv_df.head()

,Respondent,Country,ConvertedComp,LanguageWorkedWith
0,1,United Kingdom,NaN,HTML/CSS;Java;JavaScript;Python
1,2,Bosnia and Herzegovina,NaN,C++;HTML/CSS;Python
2,3,Thailand,8820.0,HTML/CSS
3,4,United States,61000.0,C;C++;C#;Python;SQL
4,5,Ukraine,NaN,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA

## Step 6: Writing to an Excel File

In [9]:
small_df.to_excel('survey_sample.xlsx', index=False)

## Step 7: Reading an Excel File Back In

In [10]:
excel_df = pd.read_excel('survey_sample.xlsx')

In [11]:
excel_df.head()

,Respondent,Country,ConvertedComp,LanguageWorkedWith
0,1,United Kingdom,NaN,HTML/CSS;Java;JavaScript;Python
1,2,Bosnia and Herzegovina,NaN,C++;HTML/CSS;Python
2,3,Thailand,8820.0,HTML/CSS
3,4,United States,61000.0,C;C++;C#;Python;SQL
4,5,Ukraine,NaN,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA

## Step 8: Writing to a JSON File

In [12]:
small_df.to_json('survey_sample.json', orient='records', lines=True)

## Step 9: Reading a JSON File Back In

In [13]:
json_df = pd.read_json('survey_sample.json', orient='records', lines=True)

In [14]:
json_df.head()

,Respondent,Country,ConvertedComp,LanguageWorkedWith
0,1,United Kingdom,NaN,HTML/CSS;Java;JavaScript;Python
1,2,Bosnia and Herzegovina,NaN,C++;HTML/CSS;Python
2,3,Thailand,8820.0,HTML/CSS
3,4,United States,61000.0,C;C++;C#;Python;SQL
4,5,Ukraine,NaN,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA

## Step 10: Writing to a SQL Database
I will use sqlite3 to create a simple local database and save my DataFrame into a table.

In [15]:
conn = sqlite3.connect('survey_sample.db')

In [16]:
small_df.to_sql('survey', conn, if_exists='replace', index=False)

50

## Step 11: Reading Data Back from SQL
I can use a normal SQL query to pull the data back out of the database and into a DataFrame.

In [17]:
sql_df = pd.read_sql('SELECT * FROM survey', conn)

In [18]:
sql_df.head()

,Respondent,Country,ConvertedComp,LanguageWorkedWith
0,1,United Kingdom,NaN,HTML/CSS;Java;JavaScript;Python
1,2,Bosnia and Herzegovina,NaN,C++;HTML/CSS;Python
2,3,Thailand,8820.0,HTML/CSS
3,4,United States,61000.0,C;C++;C#;Python;SQL
4,5,Ukraine,NaN,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA

## Step 12: Running a More Specific SQL Query

In [19]:
high_earners = pd.read_sql('SELECT * FROM survey WHERE ConvertedComp > 50000', conn)

In [20]:
high_earners

,Respondent,Country,ConvertedComp,LanguageWorkedWith
0,4,United States,61000.0,C;C++;C#;Python;SQL
1,6,Canada,366420.0,Java;R;SQL
2,9,New Zealand,95179.0,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...
3,13,United States,90000.0,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...
4,14,Germany,57060.0,C++
5,16,United Kingdom,455352.0,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;T...
6,17,Australia,65277.0,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Type...
7,22,United States,103000.0,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...
8,23,United States,69000.0,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Pyth...
9,26,United States,114000.0,Bash/Shell/PowerShell;C++;C#;HTML/CSS;JavaScri...
10,29,United States,100000.0,Bash/Shell/PowerShell;JavaScript;SQL
11,30,Switzerland,90417.0,NaN
12,32,United States,1100000.0,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...
13,35,United States,80000.0,HTML/CSS;JavaScript
14,38,Czech Republic,51312.0,C#;HTML/CSS;JavaScript;SQL
15,39,United States,156000.0,C#;JavaScript;SQL;TypeScript
16,44,Germany,87996.0,Bash/Shell/PowerShell;C#;HTML/CSS;Java;JavaScr...
17,45,United States,175000.0,Python
18,47,United States,187000.0,Java;PHP;Ruby
19,49,Serbia,60000.0,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...

## Step 13: Closing the Database Connection

In [21]:
conn.close()